pool:
  name: CENTOS-7

trigger:
- master

variables:
   imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Go'
    repository: 'GoPortal'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'