apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  namespace: #{KUBE_NAMESPACE}#
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: go
  template:
    metadata:
      labels:
        bb: go
    spec:
      containers:
      - name: go-container
        image: ttl.sh/goportal:#{Release.Artifacts.build.BuildId}#
        ports:
        - containerPort: 4444
        env:
        - name: GO_ENVIRONMENT
          value: #{GO_ENVIRONMENT}#
        volumeMounts:
        - name: go
          mountPath: /var/opt/go
      volumes:
      - name: go
        hostPath:
          path: /root/go/go
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: #{KUBE_NAMESPACE}#
spec:
  selector:
    app.kubernetes.io/name: go
  ports:
    - protocol: TCP
      port: 4444 
      targetPort: 4444
  type: LoadBalancer
  externalIPs:
   - 10.3.20.211
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: go-pv-volume
  namespace: default
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/go
    type: DirectoryOrCreate
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: go-data
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
