apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  namespace: #{KUBE_NAMESPACE}#
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: go
  template:
    metadata:
      labels:
        bb: go
    spec:
      containers:
      - name: go-container
        image: ttl.sh/goportal:#{Release.Artifacts.build.BuildId}#
        env:
        - name: GO_ENVIRONMENT
          value: #{GO_ENVIRONMENT}#
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: #{KUBE_NAMESPACE}#
spec:
  type: NodePort
  selector:
    bb: go
  ports:
  - port: 4444
    targetPort: 4444
    nodePort: #{EXPOSED_PORT}#
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: go-pv-volume
  labels:
    type: local
spec:
  storageClassName: 'go'
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/#{KUBE_NAMESPACE}#/go"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: go-data
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
